[build-system]
requires = ["setuptools>=77", "cython>=3"]
build-backend = "setuptools.build_meta"

[project]
name = "ok-ww"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
    "ok-script[ocr,qt]==2.0.0",
    "openvino",
    "opencv-python",
]

[project.optional-dependencies]
dev = [
    "polib",
    "pytest",
]
docs = [
    "mkdocs-material>=9.5,<10",
]
web-test = [
    "ok-script[web]==2.0.0b7",
]
