import time

from src.char.BaseChar import BaseChar


# Generated by AI.
class Lucilla(BaseChar):
    REMINISCENCE_TIME = 4.2

    def do_perform(self):
        if self.has_intro:
            self.continues_normal_attack(1.0)
        elif self.flying():
            self.wait_down()

        self.click_echo(time_out=0)

        if self.perform_focus_resonance():
            self.continues_normal_attack(0.4)

        if self.is_forte_full() and not self.need_fast_perform() and self.click_liberation(wait_if_cd_ready=0):
            self.perform_reminiscence()
            return self.switch_next_char()

        self.continues_normal_attack(0.8)
        if self.perform_focus_resonance():
            self.continues_normal_attack(0.2)
        self.switch_next_char()

    def perform_focus_resonance(self):
        if not self.resonance_available():
            return False
        start = time.time()
        self.task.send_key_down(self.get_resonance_key())
        try:
            while self.resonance_available() and time.time() - start < 0.75:
                self.check_combat()
                self.task.next_frame()
        finally:
            self.task.send_key_up(self.get_resonance_key())
        if not self.resonance_available():
            self.record_resonance_use()
            return True
        return False

    def perform_reminiscence(self):
        start = time.time()
        while self.time_elapsed_accounting_for_freeze(start) < self.REMINISCENCE_TIME:
            if self.need_fast_perform():
                return
            self.click(interval=0.08)
            self.check_combat()
            self.task.next_frame()
