name: AI Code Review

on:
  pull_request_target:
    types: [ opened, synchronize ]
permissions:
  contents: read
  pull-requests: write
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: AI Code Review
        uses: ok-oldking/ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Choose your AI provider and key
          AI_PROVIDER: "google" # or "anthropic" or "google"
          AI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          AI_MODEL: "gemini-2.5-flash"
          AI_TEMPERATURE: 0 # 0 to 1 - higher values = more creativity and variance

          # Optional configurations
          APPROVE_REVIEWS: true
          MAX_COMMENTS: 10 # 0 to disable
          PROJECT_CONTEXT: "This is a Node.js TypeScript project"
          CONTEXT_FILES: "README.md"
          EXCLUDE_PATTERNS: "**/*.lock,**/*.json,**/*.md,**/*.ico,**/*.png"