name: Build VSCode Solution

on:
  push:
    branches:
      - test_build_exe

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: |
        cp icon.ico src-win-launcher\icon.ico
        cd src-win-launcher
        msbuild ok-launcher.sln /p:Configuration=Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ok-ww-executable
        path: src-win-launcher/x64/Release/ok-ww.exe
