on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'lts'
      - 'v*'
    branches:
      - master

jobs:
  build:
    name: push to update repos
    runs-on: windows-latest
    steps:
      - name: Configure git
        run: |
          git config --global user.email "ok-oldking@users.noreply.github.com"
          git config --global user.name "ok-oldking"

      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.OK_GH }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Use the version of Python you need

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy ok-script lib
        run: |
          python -m ok.update.copy_ok_folder

      - name: push to test
        run: |
          python -m ok.update.push_repos --repos https://ok-oldking:${{ secrets.OK_GH }}@github.com/ok-oldking/test --files src ok config.py launcher.json launcher.py main.py ok-ww.exe main.py main_debug.py main_gpu.py main_gpu_debug.py assets i18n icon.png requirements.txt

