on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'lts'
      - 'v*'

jobs:
  build:
    name: Build exe with launcher
    runs-on: windows-latest
    steps:
      - name: Configure git
        run: |
          git config --global user.email "ok-oldking@users.noreply.github.com"
          git config --global user.name "ok-oldking"

      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.OK_GH }}
          fetch-depth: 0

      - name: Get Changes between Tags
        id: changes
        uses: simbo/changes-between-tags-action@v1
        with:
          validate-tag: false

      - name: Get tag name
        id: tagName
        uses: olegtarasov/get-tag@v2.1.3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Use the version of Python you need

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy ok-script lib
        run: |
          python -m ok.update.copy_ok_folder

      - name: amend git to add ok-script
        run: |
          $tags = git tag --points-at HEAD
          foreach ($tag in $tags) {
              git tag -d $tag
          }
          git add -f ok/
          git commit --amend --no-edit
          foreach ($tag in $tags) {
              git tag -d $tag
              git tag $tag -m "tag_$tag"
          }

      - name: Push to GitHub update
        run: |
          git remote add ghupdate https://ok-oldking:${{ secrets.OK_GH }}@github.com/ok-oldking/ok-ww-update.git
          git push ghupdate --force --tags HEAD:master 
          git push ghupdate ${{ steps.tagName.outputs.tag }}
