name: Clone and Push to Coding.net

on:
  push:
    branches:
      - '**'

jobs:
  clone-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Clone GitHub repository
        run: |
          git clone --mirror https://github.com/ok-oldking/ok-wuthering-waves.git
          cd ok-wuthering-waves.git

      - name: Set up Git credentials
        env:
          CODING_USERNAME: ${{ secrets.CODING_USERNAME }}
          CODING_PASSWORD: ${{ secrets.CODING_PASSWORD }}
        run: |
          git config --global credential.helper store
          echo "https://${CODING_USERNAME}:${CODING_PASSWORD}@e.coding.net" > ~/.git-credentials

      - name: Push to Coding.net
        run: |
          git remote add coding https://e.coding.net/g-frfh1513/ok-wuthering-waves/ok-wuthering-waves.git
          git push --mirror coding --force
