name: Sync and Push to Another Repo

on:
  push:
    branches:
      - master

jobs:
  sync-and-push:
    runs-on: windows-latest

    steps:
      - name: Configure git
        run: |
          git config --global user.email "ok-oldking@users.noreply.github.com"
          git config --global user.name "ok-oldking"

      - name: Checkout source repository
        run: |
          git clone https://github.com/ok-oldking/ok-wuthering-waves.git
          cd ok-wuthering-waves

      - name: Add destination repository as a remote
        run: |
          git remote add ghupdate https://ok-oldking:${{ secrets.OK_GH }}@github.com/ok-oldking/ok-ww-update.git

      - name: push
        run: |
          git push ghupdate --force

